#!/usr/bin/env python3

# K4 Macro program written in Python 3. It creates a set of buttons
# to send macros to the K4.  These can be simple or complex. It was
# inspired by K4 Macromaster, but in no way duplicates all the functions
# This script is a modified version of one provided by Charles, NK8O,
# It is provided without any guarantee, implied or otherwise.
#
# New buttons/macros can easily be added.
# Dale, W7DA

import socket
import tkinter as tk 

#k4_address = 'K4-SNxxxxx.local' # match your serial number in the string
k4_address = 'k4'
k4_addr_port = (k4_address, 9200)

top = tk.Tk()
top.overrideredirect(1)
frame = tk.Frame(top)
frame.pack()

columns = 5

def write(cmd):
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM) # Connect>
    try:
        client_socket.connect(k4_addr_port)
        client_socket.sendall(cmd.encode())
    except socket.gaierror:
        print("address '%s' not found" % k4_address)
    except OSError:
        print('failed to connect to K4')
    finally:
        client_socket.close()

def next_row_col():
    try:
        next_row_col.column += 1
        if next_row_col.column >= columns:
            next_row_col.column = 0
            next_row_col.row += 1
    except:
        next_row_col.row = 0
        next_row_col.column = 0
    finally:
        return next_row_col.row, next_row_col.column

# text = button text
# cmd = text string to be sent to k4 (special value "quit" terminates the program instead
# fg = foreground color (default: black)
# bg = background color (default: maroon1)
# abg = active background color (default: yellow)
def button(text='', cmd='', fg='black', bg='maroon1', abg='yellow'):
    if text == '':
        raise Exception('no text specified in call to button()')
    if cmd == '':
        raise Exception('no cmd specified in call to button()')

    if cmd == 'quit':
        command = quit
    else:
        command = lambda: write(cmd)

    button = tk.Button(frame,
                bd='4',    
                text=text, relief='raised',
                fg=fg,
                bg=bg,
                activebackground=abg,
                width='10',
                command=command)

    row, column = next_row_col()

    button.grid(row=row, column=column, padx=2, pady=2)

button(text='VFO_LOCK', cmd='LK/;', abg='red')
button(text='Mode VFO A', cmd='MD+;')
button(text='Mode VFO B', cmd='MD$+;')
button(text='ATU', cmd='SW40;', abg='red')
button(text='K4D OFF', cmd='PS0;', bg='green', abg='red1')
button(text='Exit Program', cmd='quit', bg='white', abg='red')

top.mainloop()
